//
// qgx11_func.h - X11 함수
// 2023-12-23 by kim
//
// 많은 부분을 SDL3에서 베껴왔어요 (https://www.libsdl.org/)
//

#ifndef DEF_X11_SO
#define DEF_X11_SO(name)
#endif
#ifndef DEF_X11_SO_END
#define DEF_X11_SO_END
#endif
#ifndef DEF_X11_FUNC
#define DEF_X11_FUNC(ret,name,decls,args)
#endif
#ifndef DEF_X11_VAFUNC
#define DEF_X11_VAFUNC(ret,name,arg0)
#endif

DEF_X11_SO(libX11)
DEF_X11_FUNC(XSizeHints*, XAllocSizeHints, (void), ())
DEF_X11_FUNC(XWMHints*, XAllocWMHints, (void), ())
DEF_X11_FUNC(XClassHint*, XAllocClassHint, (void), ())
DEF_X11_FUNC(int, XChangePointerControl, (Display* a, Bool b, Bool c, int d, int e, int f), (a, b, c, d, e, f))
DEF_X11_FUNC(int, XChangeProperty, (Display* a, Window b, Atom c, Atom d, int e, int f, _Xconst unsigned char* g, int h), (a, b, c, d, e, f, g, h))
DEF_X11_FUNC(Bool, XCheckIfEvent, (Display* a, XEvent *b, Bool(*c)(Display*, XEvent*, XPointer), XPointer d), (a, b, c, d))
DEF_X11_FUNC(int, XClearWindow, (Display* a, Window b), (a, b))
DEF_X11_FUNC(int, XCloseDisplay, (Display* a), (a))
DEF_X11_FUNC(int, XConvertSelection, (Display* a, Atom b, Atom c, Atom d, Window e, Time f), (a, b, c, d, e, f))
DEF_X11_FUNC(Pixmap, XCreateBitmapFromData, (Display *dpy, Drawable d, _Xconst char *data, unsigned int width, unsigned int height), (dpy, d, data, width, height))
DEF_X11_FUNC(Colormap, XCreateColormap, (Display* a, Window b, Visual* c, int d), (a, b, c, d))
DEF_X11_FUNC(Cursor, XCreatePixmapCursor, (Display* a, Pixmap b, Pixmap c, XColor* d, XColor* e, unsigned int f, unsigned int g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(Cursor, XCreateFontCursor, (Display* a, unsigned int b), (a, b))
DEF_X11_FUNC(XFontSet, XCreateFontSet, (Display* a, _Xconst char* b, char*** c, int* d, char** e), (a, b, c, d, e))
DEF_X11_FUNC(GC, XCreateGC, (Display* a, Drawable b, unsigned long c, XGCValues* d), (a, b, c, d))
DEF_X11_FUNC(XImage*, XCreateImage, (Display* a, Visual* b, unsigned int c, int d, int e, char* f, unsigned int g, unsigned int h, int i, int j), (a, b, c, d, e, f, g, h, i, j))
DEF_X11_FUNC(Window, XCreateWindow, (Display* a, Window b, int c, int d, unsigned int e, unsigned int f, unsigned int g, int h, unsigned int i, Visual* j, unsigned long k, XSetWindowAttributes* l), (a, b, c, d, e, f, g, h, i, j, k, l))
DEF_X11_FUNC(int, XDefineCursor, (Display* a, Window b, Cursor c), (a, b, c))
DEF_X11_FUNC(int, XDeleteProperty, (Display* a, Window b, Atom c), (a, b, c))
DEF_X11_FUNC(int, XDestroyWindow, (Display* a, Window b), (a, b))
DEF_X11_FUNC(int, XDisplayKeycodes, (Display* a, int* b, int* c), (a, b, c))
DEF_X11_FUNC(int, XDrawRectangle, (Display* a, Drawable b, GC c, int d, int e, unsigned int f, unsigned int g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(char*, XDisplayName, (_Xconst char* a), (a))
DEF_X11_FUNC(int, XDrawString, (Display* a, Drawable b, GC c, int d, int e, _Xconst char* f, int g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(int, XEventsQueued, (Display* a, int b), (a, b))
DEF_X11_FUNC(int, XFillRectangle, (Display* a, Drawable b, GC c, int d, int e, unsigned int f, unsigned int g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(Bool, XFilterEvent, (XEvent *event, Window w), (event, w))
DEF_X11_FUNC(int, XFlush, (Display* a), (a))
DEF_X11_FUNC(int, XFree, (void*a), (a))
DEF_X11_FUNC(int, XFreeCursor, (Display* a, Cursor b), (a, b))
DEF_X11_FUNC(void, XFreeFontSet, (Display* a, XFontSet b), (a, b))
DEF_X11_FUNC(int, XFreeGC, (Display* a, GC b), (a, b))
DEF_X11_FUNC(int, XFreeFont, (Display* a, XFontStruct* b), (a, b))
DEF_X11_FUNC(int, XFreeModifiermap, (XModifierKeymap* a), (a))
DEF_X11_FUNC(int, XFreePixmap, (Display* a, Pixmap b), (a, b))
DEF_X11_FUNC(void, XFreeStringList, (char** a), (a))
DEF_X11_FUNC(char*, XGetAtomName, (Display *a, Atom b), (a, b))
DEF_X11_FUNC(int, XGetInputFocus, (Display *a, Window *b, int *c), (a, b, c))
DEF_X11_FUNC(int, XGetErrorDatabaseText, (Display* a, _Xconst char* b, _Xconst char* c, _Xconst char* d, char* e, int f), (a, b, c, d, e, f))
DEF_X11_FUNC(XModifierKeymap*, XGetModifierMapping, (Display* a), (a))
DEF_X11_FUNC(int, XGetPointerControl, (Display* a, int* b, int* c, int* d), (a, b, c, d))
DEF_X11_FUNC(Window, XGetSelectionOwner, (Display* a, Atom b), (a, b))
DEF_X11_FUNC(XVisualInfo*, XGetVisualInfo, (Display* a, long b, XVisualInfo* c, int* d), (a, b, c, d))
DEF_X11_FUNC(Status, XGetWindowAttributes, (Display* a, Window b, XWindowAttributes* c), (a, b, c))
DEF_X11_FUNC(int, XGetWindowProperty, (Display* a, Window b, Atom c, long d, long e, Bool f, Atom g, Atom* h, int* i, unsigned long* j, unsigned long *k, unsigned char **l), (a, b, c, d, e, f, g, h, i, j, k, l))
DEF_X11_FUNC(XWMHints*, XGetWMHints, (Display* a, Window b), (a, b))
DEF_X11_FUNC(Status, XGetWMNormalHints, (Display *a, Window b, XSizeHints *c, long *d), (a, b, c, d))
DEF_X11_FUNC(int, XIfEvent, (Display* a, XEvent *b, Bool(*c)(Display*, XEvent*, XPointer), XPointer d), (a, b, c, d))
DEF_X11_FUNC(int, XGrabKeyboard, (Display* a, Window b, Bool c, int d, int e, Time f), (a, b, c, d, e, f))
DEF_X11_FUNC(int, XGrabPointer, (Display* a, Window b, Bool c, unsigned int d, int e, int f, Window g, Cursor h, Time i), (a, b, c, d, e, f, g, h, i))
DEF_X11_FUNC(int, XGrabServer, (Display* a), (a))
DEF_X11_FUNC(Status, XIconifyWindow, (Display* a, Window b, int c), (a, b, c))
DEF_X11_FUNC(KeyCode, XKeysymToKeycode, (Display* a, KeySym b), (a, b))
DEF_X11_FUNC(char*, XKeysymToString, (KeySym a), (a))
DEF_X11_FUNC(int, XInstallColormap, (Display* a, Colormap b), (a, b))
DEF_X11_FUNC(Atom, XInternAtom, (Display* a, _Xconst char* b, Bool c), (a, b, c))
DEF_X11_FUNC(XPixmapFormatValues*, XListPixmapFormats, (Display* a, int* b), (a, b))
DEF_X11_FUNC(XFontStruct*, XLoadQueryFont, (Display* a, _Xconst char* b), (a, b))
DEF_X11_FUNC(KeySym, XLookupKeysym, (XKeyEvent* a, int b), (a, b))
DEF_X11_FUNC(int, XLookupString, (XKeyEvent* a, char* b, int c, KeySym* d, XComposeStatus* e), (a, b, c, d, e))
DEF_X11_FUNC(int, XMapRaised, (Display* a, Window b), (a, b))
DEF_X11_FUNC(Status, XMatchVisualInfo, (Display* a, int b, int c, int d, XVisualInfo* e), (a, b, c, d, e))
DEF_X11_FUNC(int, XMissingExtension, (Display* a, _Xconst char* b), (a, b))
DEF_X11_FUNC(int, XMoveWindow, (Display* a, Window b, int c, int d), (a, b, c, d))
DEF_X11_FUNC(Display*, XOpenDisplay, (_Xconst char* a), (a))
DEF_X11_FUNC(Status, XInitThreads, (void), ())
DEF_X11_FUNC(int, XPeekEvent, (Display* a, XEvent* b), (a, b))
DEF_X11_FUNC(int, XPending, (Display* a), (a))
DEF_X11_FUNC(int, XPutImage, (Display* a, Drawable b, GC c, XImage* d, int e, int f, int g, int h, unsigned int i, unsigned int j), (a, b, c, d, e, f, g, h, i, j))
DEF_X11_FUNC(int, XQueryKeymap, (Display* a, char *b), (a, b))
DEF_X11_FUNC(Bool, XQueryPointer, (Display* a, Window b, Window* c, Window* d, int* e, int* f, int* g, int* h, unsigned int* i), (a, b, c, d, e, f, g, h, i))
DEF_X11_FUNC(int, XRaiseWindow, (Display* a, Window b), (a, b))
DEF_X11_FUNC(int, XReparentWindow, (Display* a, Window b, Window c, int d, int e), (a, b, c, d, e))
DEF_X11_FUNC(int, XResetScreenSaver, (Display* a), (a))
DEF_X11_FUNC(int, XResizeWindow, (Display* a, Window b, unsigned int c, unsigned int d), (a, b, c, d))
DEF_X11_FUNC(int, XScreenNumberOfScreen, (Screen* a), (a))
DEF_X11_FUNC(int, XSelectInput, (Display* a, Window b, long c), (a, b, c))
DEF_X11_FUNC(Status, XSendEvent, (Display* a, Window b, Bool c, long d, XEvent* e), (a, b, c, d, e))
DEF_X11_FUNC(XErrorHandler, XSetErrorHandler, (XErrorHandler a), (a))
DEF_X11_FUNC(int, XSetForeground, (Display* a, GC b, unsigned long c), (a, b, c))
DEF_X11_FUNC(XIOErrorHandler, XSetIOErrorHandler, (XIOErrorHandler a), (a))
DEF_X11_FUNC(int, XSetInputFocus, (Display *a, Window b, int c, Time d), (a, b, c, d))
DEF_X11_FUNC(int, XSetSelectionOwner, (Display* a, Atom b, Window c, Time d), (a, b, c, d))
DEF_X11_FUNC(int, XSetTransientForHint, (Display* a, Window b, Window c), (a, b, c))
DEF_X11_FUNC(void, XSetTextProperty, (Display* a, Window b, XTextProperty* c, Atom d), (a, b, c, d))
DEF_X11_FUNC(int, XSetWindowBackground, (Display* a, Window b, unsigned long c), (a, b, c))
DEF_X11_FUNC(void, XSetWMHints, (Display* a, Window b, XWMHints* c), (a, b, c))
DEF_X11_FUNC(void, XSetWMNormalHints, (Display* a, Window b, XSizeHints* c), (a, b, c))
DEF_X11_FUNC(void, XSetWMProperties, (Display* a, Window b, XTextProperty* c, XTextProperty* d, char** e, int f, XSizeHints* g, XWMHints* h, XClassHint* i), (a, b, c, d, e, f, g, h, i))
DEF_X11_FUNC(Status, XSetWMProtocols, (Display* a, Window b, Atom* c, int d), (a, b, c, d))
DEF_X11_FUNC(int, XStoreColors, (Display* a, Colormap b, XColor* c, int d), (a, b, c, d))
DEF_X11_FUNC(int, XStoreName, (Display* a, Window b, _Xconst char* c), (a, b, c))
DEF_X11_FUNC(Status, XStringListToTextProperty, (char** a, int b, XTextProperty* c), (a, b, c))
DEF_X11_FUNC(int, XSync, (Display* a, Bool b), (a, b))
DEF_X11_FUNC(int, XTextExtents, (XFontStruct* a, _Xconst char* b, int c, int* d, int* e, int* f, XCharStruct* g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(Bool, XTranslateCoordinates, (Display *a, Window b, Window c, int d, int e, int* f, int* g, Window* h), (a, b, c, d, e, f, g, h))
DEF_X11_FUNC(int, XUndefineCursor, (Display* a, Window b), (a, b))
DEF_X11_FUNC(int, XUngrabKeyboard, (Display* a, Time b), (a, b))
DEF_X11_FUNC(int, XUngrabPointer, (Display* a, Time b), (a, b))
DEF_X11_FUNC(int, XUngrabServer, (Display* a), (a))
DEF_X11_FUNC(int, XUninstallColormap, (Display* a, Colormap b), (a, b))
DEF_X11_FUNC(int, XUnloadFont, (Display* a, Font b), (a, b))
DEF_X11_FUNC(int, XWarpPointer, (Display* a, Window b, Window c, int d, int e, unsigned int f, unsigned int g, int h, int i), (a, b, c, d, e, f, g, h, i))
DEF_X11_FUNC(int, XWindowEvent, (Display* a, Window b, long c, XEvent* d), (a, b, c, d))
DEF_X11_FUNC(Status, XWithdrawWindow, (Display* a, Window b, int c), (a, b, c))
DEF_X11_FUNC(VisualID, XVisualIDFromVisual, (Visual* a), (a))
DEF_X11_FUNC(char*, XGetDefault, (Display* a, _Xconst char* b, _Xconst char* c), (a, b, c))
DEF_X11_FUNC(Bool, XQueryExtension, (Display* a, _Xconst char* b, int* c, int* d, int* e), (a, b, c, d, e))
DEF_X11_FUNC(char *, XDisplayString, (Display* a), (a))
DEF_X11_FUNC(int, XGetErrorText, (Display* a, int b, char* c, int d), (a, b, c, d))
DEF_X11_FUNC(void, _XEatData, (Display* a, unsigned long b), (a, b))
DEF_X11_FUNC(void, _XFlush, (Display* a), (a))
DEF_X11_FUNC(void, _XFlushGCCache, (Display* a, GC b), (a, b))
DEF_X11_FUNC(int, _XRead, (Display* a, char* b, long c), (a, b, c))
DEF_X11_FUNC(void, _XReadPad, (Display* a, char* b, long c), (a, b, c))
DEF_X11_FUNC(void, _XSend, (Display* a, _Xconst char* b, long c), (a, b, c))
DEF_X11_FUNC(Status, _XReply, (Display* a, xReply* b, int c, Bool d), (a, b, c, d))
DEF_X11_FUNC(unsigned long, _XSetLastRequestRead, (Display* a, xGenericReply* b), (a, b))
DEF_X11_FUNC(void, XRefreshKeyboardMapping, (XMappingEvent *a), (a))
DEF_X11_FUNC(int, XQueryTree, (Display* a, Window b, Window* c, Window* d, Window** e, unsigned int* f), (a, b, c, d, e, f))
DEF_X11_FUNC(Bool, XSupportsLocale, (void), ())
DEF_X11_FUNC(Status, XmbTextListToTextProperty, (Display* a, char** b, int c, XICCEncodingStyle d, XTextProperty* e), (a, b, c, d, e))
DEF_X11_FUNC(int, Xutf8TextListToTextProperty, (Display * a, char** b, int c, XICCEncodingStyle d, XTextProperty * e), (a, b, c, d, e))
DEF_X11_FUNC(int, Xutf8LookupString, (XIC a, XKeyPressedEvent * b, char* c, int d, KeySym * e, Status * f), (a, b, c, d, e, f))
DEF_X11_VAFUNC(XIC, XCreateIC, XIM)
DEF_X11_FUNC(void, XDestroyIC, (XIC a), (a))
DEF_X11_VAFUNC(char*, XGetICValues, XIC)
DEF_X11_FUNC(void, XSetICFocus, (XIC a), (a))
DEF_X11_FUNC(void, XUnsetICFocus, (XIC a), (a))
DEF_X11_FUNC(XIM, XOpenIM, (Display * a, struct _XrmHashBucketRec* b, char* c, char* d), (a, b, c, d))
DEF_X11_FUNC(Status, XCloseIM, (XIM a), (a))
DEF_X11_FUNC(void, Xutf8DrawString, (Display * a, Drawable b, XFontSet c, GC d, int e, int f, _Xconst char *g, int h), (a, b, c, d, e, f, g, h))
DEF_X11_FUNC(int, Xutf8TextExtents, (XFontSet a, _Xconst char* b, int c, XRectangle * d, XRectangle * e), (a, b, c, d, e))
DEF_X11_FUNC(char*, XSetLocaleModifiers, (const char *a), (a))
DEF_X11_FUNC(char*, Xutf8ResetIC, (XIC a), (a))
DEF_X11_SO_END

DEF_X11_SO(libXfixes)
DEF_X11_FUNC(PointerBarrier, XFixesCreatePointerBarrier, (Display* a, Window b, int c, int d, int e, int f, int g, int h, int *i), (a, b, c, d, e, f, g, h, i))
DEF_X11_FUNC(void, XFixesDestroyPointerBarrier, (Display* a, PointerBarrier b), (a, b))
DEF_X11_FUNC(Status, XFixesQueryVersion, (Display * a, int* b, int* c), (a, b, c))
DEF_X11_FUNC(Bool, XGetEventData, (Display * a, XGenericEventCookie * b), (a, b))
DEF_X11_FUNC(void, XFreeEventData, (Display * a, XGenericEventCookie * b), (a, b))
DEF_X11_FUNC(Bool, XkbQueryExtension, (Display * a, int * b, int * c, int * d, int * e, int *f), (a, b, c, d, e, f))
#if NeedWidePrototypes
DEF_X11_FUNC(KeySym, XkbKeycodeToKeysym, (Display * a, unsigned int b, int c, int d), (a, b, c, d))
#else
DEF_X11_FUNC(KeySym, XkbKeycodeToKeysym, (Display * a, KeyCode b, int c, int d), (a, b, c, d))
#endif
DEF_X11_FUNC(Status, XkbGetState, (Display * a, unsigned int b, XkbStatePtr c), (a, b, c))
DEF_X11_FUNC(Status, XkbGetUpdatedMap, (Display * a, unsigned int b, XkbDescPtr c), (a, b, c))
DEF_X11_FUNC(XkbDescPtr, XkbGetMap, (Display * a, unsigned int b, unsigned int c), (a, b, c))
DEF_X11_FUNC(void, XkbFreeClientMap, (XkbDescPtr a, unsigned int b, Bool c), (a, b, c))
DEF_X11_FUNC(void, XkbFreeKeyboard, (XkbDescPtr a, unsigned int b, Bool c), (a, b, c))
DEF_X11_FUNC(Bool, XkbSetDetectableAutoRepeat, (Display * a, Bool b, Bool * c), (a, b, c))
#if NeedWidePrototypes
DEF_X11_FUNC(KeySym, XKeycodeToKeysym, (Display * a, unsigned int b, int c), (a, b, c))
#else
DEF_X11_FUNC(KeySym, XKeycodeToKeysym, (Display * a, KeyCode b, int c), (a, b, c))
#endif
DEF_X11_SO_END

DEF_X11_SO(libXext)
DEF_X11_FUNC(Status, XShmAttach, (Display * a, XShmSegmentInfo * b), (a, b))
DEF_X11_FUNC(Status, XShmDetach, (Display * a, XShmSegmentInfo * b), (a, b))
DEF_X11_FUNC(Status, XShmPutImage, (Display * a, Drawable b, GC c, XImage * d, int e, int f, int g, int h, unsigned int i, unsigned int j, Bool k), (a, b, c, d, e, f, g, h, i, j, k))
DEF_X11_FUNC(XImage*, XShmCreateImage, (Display * a, Visual * b, unsigned int c, int d, char* e, XShmSegmentInfo * f, unsigned int g, unsigned int h), (a, b, c, d, e, f, g, h))
DEF_X11_FUNC(Pixmap, XShmCreatePixmap, (Display * a, Drawable b, char* c, XShmSegmentInfo * d, unsigned int e, unsigned int f, unsigned int g), (a, b, c, d, e, f, g))
DEF_X11_FUNC(Bool, XShmQueryExtension, (Display * a), (a))
DEF_X11_FUNC(Status, XdbeQueryExtension, (Display * dpy, int *major_version_return, int *minor_version_return), (dpy, major_version_return, minor_version_return))
DEF_X11_FUNC(XdbeBackBuffer, XdbeAllocateBackBufferName, (Display * dpy, Window window, XdbeSwapAction swap_action), (dpy, window, swap_action))
DEF_X11_FUNC(Status, XdbeDeallocateBackBufferName, (Display * dpy, XdbeBackBuffer buffer), (dpy, buffer))
DEF_X11_FUNC(Status, XdbeSwapBuffers, (Display * dpy, XdbeSwapInfo * swap_info, int num_windows), (dpy, swap_info, num_windows))
DEF_X11_FUNC(Status, XdbeBeginIdiom, (Display * dpy), (dpy))
DEF_X11_FUNC(Status, XdbeEndIdiom, (Display * dpy), (dpy))
DEF_X11_FUNC(XdbeScreenVisualInfo*, XdbeGetVisualInfo, (Display * dpy, Drawable * screen_specifiers, int *num_screens), (dpy, screen_specifiers, num_screens))
DEF_X11_FUNC(void, XdbeFreeVisualInfo, (XdbeScreenVisualInfo * visual_info), (visual_info))
DEF_X11_FUNC(XdbeBackBufferAttributes*, XdbeGetBackBufferAttributes, (Display * dpy, XdbeBackBuffer buffer), (dpy, buffer))
DEF_X11_FUNC(void, XShapeCombineMask, (Display * dpy, Window dest, int dest_kind, int x_off, int y_off, Pixmap src, int op), (dpy, dest, dest_kind, x_off, y_off, src, op))
DEF_X11_SO_END

DEF_X11_SO(libXcursor)
DEF_X11_FUNC(XcursorImage*, XcursorImageCreate, (int a, int b), (a, b))
DEF_X11_FUNC(void, XcursorImageDestroy, (XcursorImage * a), (a))
DEF_X11_FUNC(Cursor, XcursorImageLoadCursor, (Display * a, const XcursorImage * b), (a, b))
DEF_X11_SO_END

DEF_X11_SO(libXrandr)
DEF_X11_FUNC(Status, XRRQueryVersion, (Display * dpy, int *major_versionp, int *minor_versionp), (dpy, major_versionp, minor_versionp))
DEF_X11_FUNC(Bool, XRRQueryExtension, (Display * dpy, int *event_base_return, int *error_base_return), (dpy, event_base_return, error_base_return))
DEF_X11_FUNC(XRRScreenConfiguration *, XRRGetScreenInfo, (Display * dpy, Drawable draw), (dpy, draw))
DEF_X11_FUNC(SizeID, XRRConfigCurrentConfiguration, (XRRScreenConfiguration * config, Rotation * rotation), (config, rotation))
DEF_X11_FUNC(short, XRRConfigCurrentRate, (XRRScreenConfiguration * config), (config))
DEF_X11_FUNC(short *, XRRConfigRates, (XRRScreenConfiguration * config, int sizeID, int *nrates), (config, sizeID, nrates))
DEF_X11_FUNC(XRRScreenSize *, XRRConfigSizes, (XRRScreenConfiguration * config, int *nsizes), (config, nsizes))
DEF_X11_FUNC(Status, XRRSetScreenConfigAndRate, (Display * dpy, XRRScreenConfiguration * config, Drawable draw, int size_index, Rotation rotation, short rate, Time timestamp), (dpy, config, draw, size_index, rotation, rate, timestamp))
DEF_X11_FUNC(void, XRRFreeScreenConfigInfo, (XRRScreenConfiguration * config), (config))
DEF_X11_FUNC(void, XRRSetScreenSize, (Display * dpy, Window window, int width, int height, int mmWidth, int mmHeight), (dpy, window, width, height, mmWidth, mmHeight))
DEF_X11_FUNC(Status, XRRGetScreenSizeRange, (Display * dpy, Window window, int *minWidth, int *minHeight, int *maxWidth, int *maxHeight), (dpy, window, minWidth, minHeight, maxWidth, maxHeight))
DEF_X11_FUNC(XRRScreenResources *, XRRGetScreenResources, (Display * dpy, Window window), (dpy, window))
DEF_X11_FUNC(XRRScreenResources *, XRRGetScreenResourcesCurrent, (Display * dpy, Window window), (dpy, window))
DEF_X11_FUNC(void, XRRFreeScreenResources, (XRRScreenResources * resources), (resources))
DEF_X11_FUNC(XRROutputInfo *, XRRGetOutputInfo, (Display * dpy, XRRScreenResources * resources, RROutput output), (dpy, resources, output))
DEF_X11_FUNC(void, XRRFreeOutputInfo, (XRROutputInfo * outputInfo), (outputInfo))
DEF_X11_FUNC(XRRCrtcInfo *, XRRGetCrtcInfo, (Display * dpy, XRRScreenResources * resources, RRCrtc crtc), (dpy, resources, crtc))
DEF_X11_FUNC(void, XRRFreeCrtcInfo, (XRRCrtcInfo * crtcInfo), (crtcInfo))
DEF_X11_FUNC(Status, XRRSetCrtcConfig, (Display * dpy, XRRScreenResources * resources, RRCrtc crtc, Time timestamp, int x, int y, RRMode mode, Rotation rotation, RROutput * outputs, int noutputs), (dpy, resources, crtc, timestamp, x, y, mode, rotation, outputs, noutputs))
DEF_X11_FUNC(Atom*, XRRListOutputProperties, (Display * dpy, RROutput output, int *nprop), (dpy, output, nprop))
DEF_X11_FUNC(XRRPropertyInfo*, XRRQueryOutputProperty, (Display * dpy, RROutput output, Atom property), (dpy, output, property))
DEF_X11_FUNC(int, XRRGetOutputProperty, (Display * dpy, RROutput output, Atom property, long offset, long length, Bool _delete, Bool pending, Atom req_type, Atom * actual_type, int *actual_format, unsigned long *nitems, unsigned long *bytes_after, unsigned char **prop), (dpy, output, property, offset, length, _delete, pending, req_type, actual_type, actual_format, nitems, bytes_after, prop))
DEF_X11_FUNC(RROutput, XRRGetOutputPrimary, (Display * dpy, Window window), (dpy, window))
DEF_X11_FUNC(void, XRRSelectInput, (Display * dpy, Window window, int mask), (dpy, window, mask))
DEF_X11_SO_END

DEF_X11_SO(libXss)
DEF_X11_FUNC(Bool, XScreenSaverQueryExtension, (Display * dpy, int *event_base, int *error_base), (dpy, event_base, error_base))
DEF_X11_FUNC(Status, XScreenSaverQueryVersion, (Display * dpy, int *major_versionp, int *minor_versionp), (dpy, major_versionp, minor_versionp))
DEF_X11_FUNC(void, XScreenSaverSuspend, (Display * dpy, Bool suspend), (dpy, suspend))
DEF_X11_SO_END

#undef DEF_X11_VAFUNC
#undef DEF_X11_FUNC
#undef DEF_X11_SO_END
#undef DEF_X11_SO
